[package]
name = "nexer"
version = "1.1.0" # I forget to update this
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3

[lib]
doctest = false


